config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  get :sign_up, :to => "accounts#new"
  get :login,   :to => "sessions#new"

  resources :accounts
  resources :children
  resource :session
end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :adults
end

app/models/adult.rb
class Adult < ActiveRecord::Base
  belongs_to :account
  has_one :credential, :as => :owner
end

app/models/credential.rb
class Credential < ActiveRecord::Base
  has_secure_password

  belongs_to :owner, :polymorphic => true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def new
    @form = Accounts::SignUpForm.new
  end

  def create
    @form = Accounts::SignUpForm.from_params(params)

    Accounts::SignUp.call(@form) do
      on(:ok)      { redirect_to children_path, :notice => t(:signed_up) }
      on(:invalid) { render :new }

      on(:race_non_unique_email) do
        flash.now[:alert] = t(:email_taken)
        render :new
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery :with => :exception
end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/views/accounts/new.html.slim
= content_for :title do
  | Sign up


.row
  .col-md-12
    h1 Sign up

.row
  .col-md-12
    = simple_form_for @form do |f|
      = f.input :first_name
      = f.input :last_name
      = f.input :email
      = f.input :password
      = f.input :password_confirmation

      = f.button :submit_with_cancel, :cancel => root_path

app/views/application/_flash.html.slim
- if flash[:notice].present?
  .alert.alert-success.flash.alert-dismissible role="alert"
    .container
      button.close type="button" data-dismiss="alert" aria-label="Close"
        span aria-hidden="true" &times;
      = flash[:notice]

- if flash[:alert].present?
  .alert.alert-danger.flash.alert-dismissible role="alert"
    .container
      button.close type="button" data-dismiss="alert" aria-label="Close"
        span aria-hidden="true" &times;
      = flash[:alert]

app/views/application/_menu.html.slim
nav.navbar.navbar-default
  .container
    .navbar-header
      a.navbar-brand href="#"
        | Smarty Pants
    .collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        li= link_to "Sign up", sign_up_path

app/views/children/index.html.slim
h1 Children

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta content="IE=edge" http-equiv="X-UA-Compatible"
    meta content="width=device-width, initial-scale=1.0" name="viewport"

    title= yield(:title).presence || "Smarty Pants"

    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags

  body
    = render "menu"
    = render "flash"

    .container
      = yield

app/views/pages/home.html.slim
h1 Smarty Pants